apiVersion: v1
kind: Service
metadata:
  labels:
    app: quorum-operation-executor
    environment: Development
  name: quorum-operation-executor
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: quorum-operation-executor
  sessionAffinity: None
  type: ClusterIP
